FROM node:14 AS build-stage

WORKDIR /app

COPY package.json /app/package.json

COPY src/ /app/src
COPY public/ /app/public
COPY environments/.env.production /app/environments/.env.production
COPY yarn.lock /app/yarn.lock
COPY tsconfig.json /app/tsconfig.json

#install dependencies
RUN yarn install

#build production app
RUN yarn run build



FROM flashspys/nginx-static
RUN apk update && apk upgrade

COPY --from=0 app/build /static

RUN rm -rf /etc/nginx/conf.d/default.conf
COPY .docker/default.conf /etc/nginx/conf.d/default.conf
